language: scala

scala:
   - 2.10.7
   - 2.11.12

jdk:
   - oraclejdk10
   - oraclejdk8
   - oraclejdk7
   - openjdk7

before_install:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

install:
   - |
      pushd /tmp
      git clone -q --branch=4.0-RC1 --depth=2 -- https://github.com/rayrobdod/json.git json
      cd json
      echo sbt.version=0.13.17>project/build.properties
      sbt ++$TRAVIS_SCALA_VERSION publishLocal
      popd
   - |
      pushd /tmp
      git clone -q --branch=master --depth=50 -- https://github.com/rayrobdod/boardGame.git boardGame
      cd boardGame
      git checkout -q 07a3f9ea46dd355b0583e72b15f1aac6b22900c9
      sbt ++$TRAVIS_SCALA_VERSION publishLocal
      popd
   - |
      pushd /tmp
      git clone -q --branch=20160112 --depth=2 -- https://github.com/rayrobdod/utilities.git utilities
      cd utilities
      echo sbt.version=0.13.17>project/build.properties
      sbt ++$TRAVIS_SCALA_VERSION publishLocal
      popd
   - sbt ++$TRAVIS_SCALA_VERSION update

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate coveralls
