version: 'yml.{build}'
os: Windows Server 2012
install:
  - cmd: choco install --limit-output sbt --version 0.13.15
  - cmd: C:\cygwin64\setup-x86_64.exe --no-admin -q -P graphviz
  - cmd: refreshenv
  - |
     mkdir %USERPROFILE%\.sbt\0.13
     echo scalacOptions in doc in Compile ++= Seq("-diagrams-dot-path", """C:\cygwin64\bin\dot.exe""")>%USERPROFILE%\.sbt\0.13\dot.sbt
     echo publishTo in Global := {val patterns = if (publishMavenStyle.value) {sbt.Resolver.mavenStylePatterns} else {sbt.Resolver.ivyStylePatterns}; Some(Resolver.file("file", file("""C:\projects\deductionTactics\publish"""))(patterns) )}>%USERPROFILE%\.sbt\0.13\pubdir.sbt
  - |
     cd C:\projects
     git clone --branch=4.0-RC1 --depth=2 -- https://github.com/rayrobdod/json.git json
     cd json
     echo sbt.version=0.13.17>project/build.properties
     sbt ++%SCALA_VERSION% publishLocal
     cd C:\projects\deductionTactics
  - |
     cd C:\projects
     git clone --branch=fromJsonBuilders --depth=10 -- https://github.com/rayrobdod/boardGame.git boardGame
     cd boardGame
     git checkout 5d0cc695e7c558502284ae547d10d849a029cece
     sbt ++%SCALA_VERSION% publishLocal
     cd C:\projects\deductionTactics
  - |
     cd C:\projects
     git clone --branch=20160112 --depth=2 -- https://github.com/rayrobdod/utilities.git utilities
     cd utilities
     echo sbt.version=0.13.17>project/build.properties
     sbt ++%SCALA_VERSION% publishLocal
     cd C:\projects\deductionTactics
  - cmd: sbt ++%SCALA_VERSION% update

environment:
  matrix:
  - SCALA_VERSION: 2.10.6
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
    SBT_CROSS_TARGET: scala-2.10
  - SCALA_VERSION: 2.11.7
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
    SBT_CROSS_TARGET: scala-2.11
build_script:
  - cmd: 'sbt ++%SCALA_VERSION% compile publish'
test_script:
  # primary purpose is to package, but might as well test too, I guess.
  - cmd: 'sbt ++%SCALA_VERSION% test'
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $files=get-childitem .\target\$($env:SBT_CROSS_TARGET)\test-results-junit
      foreach ($file in $files) {
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\target\$($env:SBT_CROSS_TARGET)\test-results-junit\$file))
      }
artifacts:
  - path: publish
    name: sbt_publish_directory
  - path: proguard
    name: proguarded_file
cache:
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
