[
	{
		"name":"Ninja",
		"element":"Sound",
		"atkWeapon":"Blade",
		"atkStatus":"Confuse",
		"range":1,
		"speed":5,
		"body":"Human",
		"weakWeapon":{"blade":1 ,"blunt":.5,"spear":1.75,"whip":2},
		"weakStatus":"Neuro",
		"weakDirection":"<?php echo $directions[rand(0,3)]?>",
		"icon":"/sprites/classes/Ninja.png"
	},
	{
		"name":"Farmer",
		"element":"Light",
		"atkWeapon":"Spear",
		"atkStatus":"Snake",
		"range":1,
		"speed":3,
		"body":"Human",
		"weakWeapon":{"blade":1.5 ,"blunt":.5,"spear":.75 ,"whip":2},
		"weakStatus":"Blind",
		"weakDirection":"<?php echo $directions[rand(0,3)]?>",
		"icon":"/sprites/classes/Farmer.png"
	},
	{
		"name":"Umbreallaswordsman",
		"element":"Frost",
		"atkWeapon":"Blade",
		"atkStatus":"Blind",
		"range":1,
		"speed":3,
		"body":"Human",
		"weakWeapon":{"blade":1.5,"blunt":.5,"spear":2 ,"whip":.5},
		"weakStatus":"Blind",
		"weakDirection":"Down",
		"icon":"/sprites/classes/Umbrellaswordsman.png"
	},
	{
		"name":"Umbreallagunsman",
		"element":"Frost",
		"atkWeapon":"Spear",
		"atkStatus":"Confuse",
		"range":2,
		"speed":3,
		"body":"Human",
		"weakWeapon":{"blade":1.5,"blunt":1,"spear":2 ,"whip":1},
		"weakStatus":"Blind",
		"weakDirection":"Down",
		"icon":"/sprites/classes/Farmer.png"
	},
	{
		"name":"Pyro",
		"element":"Fire",
		"atkWeapon":"Powder",
		"atkStatus":"Burn",
		"range":2,
		"speed":2,
		"body":"Human",
		"weakWeapon":{"blade":2,"blunt":1.5,"spear":.5 ,"whip":.5},
		"weakStatus":"Neuro",
		"weakDirection":"<?php echo $directions[rand(0,3)]?>",
		"icon":"/sprites/classes/Farmer.png"
	},
	{
		"name":"Torchbearer",
		"element":"Fire",
		"atkWeapon":"Blunt",
		"atkStatus":"Burn",
		"range":1,
		"speed":3,
		"body":"Human",
		"weakWeapon":{"blade":.75,"blunt":.5,"spear":1.5 ,"whip":2},
		"weakStatus":"Sleep",
		"weakDirection":"<?php echo $directions[rand(0,3)]?>",
		"icon":"/sprites/classes/Farmer.png"
	},
	{
		"name":"Yoyoer",
		"element":"Light",
		"atkWeapon":"Whip",
		"atkStatus":"Confuse",
		"range":1,
		"speed":3,
		"body":"Human",
		"weakWeapon":{"blade":2,"blunt":.5,"spear":1.5 ,"whip":1},
		"weakStatus":"Confuse",
		"weakDirection":"<?php echo $directions[rand(0,3)]?>",
		"icon":"/sprites/classes/Farmer.png"
	},
	{
		"name":"Flashlightman",
		"element":"Light",
		"atkWeapon":"Powder",
		"atkStatus":"Blind",
		"range":2,
		"speed":3,
		"body":"Human",
		"weakWeapon":{"blade":1,"blunt":1.5,"spear":2 ,"whip":.5},
		"weakStatus":"Confuse",
		"weakDirection":"<?php echo $directions[rand(0,3)]?>",
		"icon":"/sprites/classes/Farmer.png"
	},
	{
		"name":"Pikachu Cosplayer",
		"element":"Electric",
		"atkWeapon":"Whip",
		"atkStatus":"Neurotoxin",
		"range":2,
		"speed":3,
		"body":"Human",
		"weakWeapon":{"blade":2,"blunt":1,"spear":1.5 ,"whip":.75},
		"weakStatus":"Confuse",
		"weakDirection":"<?php echo $directions[rand(0,3)]?>",
		"icon":"/sprites/classes/Farmer.png"
	},
	{
		"name":"Entei Shirt Guy",
		"element":"Fire",
		"atkWeapon":"Blunt",
		"atkStatus":"Confuse",
		"range":1,
		"speed":5,
		"body":"Human",
		"weakWeapon":{"blade":1.5,"blunt":.75,"spear":2 ,"whip":.5},
		"weakStatus":"Snake",
		"weakDirection":"<?php echo $directions[rand(0,3)]?>",
		"icon":"/sprites/classes/Farmer.png"
	},
	{
		"name":"Medic",
		"element":"Light",
		"atkWeapon":"Blunt",
		"atkStatus":"Heal", "comment": "It's not possible to attack your own units, so this is very counter productive",
		"range":1,
		"speed":3,
		"body":"Human",
		"weakWeapon":???,
		"weakStatus":"Confuse",
		"weakDirection":"<?php echo $directions[rand(0,3)]?>",
		"icon":"/sprites/classes/Farmer.png"
	}
]